import { addIcons } from 'oh-vue-icons'
import {
  FaCloudversify,
  FaAngleDown,
  FaAngleUp,
  BiArrowCounterclockwise,
  BiArrowClockwise,
  BiPlayCircleFill,
  BiBadgeCc,
  BiClipboard2,
  FaRegularSave,
  BiSearch,
  BiThreeDots,
  FaRegularEdit,
  BiUpload,
  GiBookshelf,
  BiPeople,
  BiPerson,
  BiGearFill,
  BiPlay,
  RiUserVoiceLine,
  BiPause,
  BiPauseCircleFill,
} from 'oh-vue-icons/icons'


export function importIcons() {
  addIcons(
    FaCloudversify,
    FaAngleDown,
    FaAngleUp,
    BiArrowCounterclockwise,
    BiArrowClockwise,
    BiPlayCircleFill,
    BiPauseCircleFill,
    BiBadgeCc,
    BiClipboard2,
    FaRegularSave,
    BiSearch,
    BiThreeDots,
    FaRegularEdit,
    BiUpload,
    GiBookshelf,
    BiPeople,
    BiPerson,
    BiGearFill,
    BiSearch,
    BiPlay,
    RiUserVoiceLine,
    BiPause,
  )
}
